apiVersion: v1
kind: Template
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: https://github.com/dummy_org/dummy_repo
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: The secret used to configure a GitHub webhook
    displayName: GitHub Webhook Secret
    required: true
    from: "[a-zA-Z0-9]{40}"
    generate: expression
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: testing-database-bind
      labels:
        app: testing
    stringData:
      uri: testing-database
      database: my_data
      user: dbuser
      password: secret
  - kind: ImageStreamTag
    apiVersion: v1
    metadata:
      name: testing-database:5.7
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
        openshift.io/imported-from: 172.30.1.1:5000/openshift/mysql:5.7
    tag:
      name: "5.7"
      annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/openshift/mysql:5.7
      generation: null
      importPolicy:
        {}
      referencePolicy:
        type: ""
    generation: 0
    lookupPolicy:
      local: false
    image:
      metadata:
        creationTimestamp: null
      dockerImageMetadata:
        kind: DockerImage
        apiVersion: "1.0"
        Id: ""
        Created: null
        ContainerConfig:
          {}
      dockerImageMetadataVersion: "1.0"
      dockerImageLayers: null
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: testing-database
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      strategy:
        resources:
          {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - testing-database
            from:
              kind: ImageStreamTag
              namespace: openshift
              name: mysql:5.7
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: testing-database
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: testing-database
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
        spec:
          containers:
            - name: testing-database
              image: 172.30.1.1:5000/openshift/mysql:5.7
              ports:
                - containerPort: 3306
                  protocol: TCP
              resources:
                {}
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: verysecretrootpassword
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: testing-database-bind
                      key: database
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: testing-database-bind
                      key: user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: testing-database-bind
                      key: password
                - name: MY_DATABASE_SERVICE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: testing-database-bind
                      key: uri
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: testing-database-bind
                      key: user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: testing-database-bind
                      key: password
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: testing-database
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      ports:
        - name: 3306-tcp
          protocol: TCP
          port: 3306
          targetPort: 3306
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: testing-database
    status:
      loadBalancer:
        {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: openjdk18-openshift
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          annotations:
            openshift.io/imported-from: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
          from:
            kind: DockerImage
            name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
          generation: null
          importPolicy:
            {}
          referencePolicy:
            type: ""
    status:
      dockerImageRepository: ""
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: testing-vertx
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: testing-vertx
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      triggers:
        - type: GitHub
          github:
            secret: ${GITHUB_WEBHOOK_SECRET}
        - type: ConfigChange
        - type: ImageChange
          imageChange:
            {}
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: openjdk18-openshift:latest
          incremental: true
      output:
        to:
          kind: ImageStreamTag
          name: testing-vertx:latest
      resources:
        {}
      postCommit:
        {}
      nodeSelector: null
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: testing-vertx
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      strategy:
        resources:
          {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - testing-vertx
            from:
              kind: ImageStreamTag
              name: testing-vertx:latest
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: testing-vertx
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: testing-vertx
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
        spec:
          containers:
            - name: testing-vertx
              image: testing-vertx:latest
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              resources:
                {}
              env:
                []
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: testing-vertx
      creationTimestamp: null
      labels:
        app: testing
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: 8443-tcp
          protocol: TCP
          port: 8443
          targetPort: 8443
        - name: 8778-tcp
          protocol: TCP
          port: 8778
          targetPort: 8778
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: testing-vertx
    status:
      loadBalancer:
        {}
  - apiVersion: v1
    kind: Route
    metadata:
      name: testing-route
      labels:
        app: testing
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: testing-vertx
