apiVersion: v1
kind: Template
parameters:
  []
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: centos7-s2i-web-app
      creationTimestamp: null
      labels:
        app: testing
        apptype: welcome
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          annotations:
            openshift.io/imported-from: bucharestgold/centos7-s2i-web-app
          from:
            kind: DockerImage
            name: bucharestgold/centos7-s2i-web-app
          generation: null
          importPolicy:
            {}
          referencePolicy:
            type: ""
    status:
      dockerImageRepository: ""
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: testing-welcome
      creationTimestamp: null
      labels:
        app: testing
        apptype: welcome
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: testing-welcome
      creationTimestamp: null
      labels:
        app: testing
        apptype: welcome
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange:
            {}
      source:
        type: Git
        git:
          uri: https://github.com/fabric8-launcher/launcher-creator-welcome-app
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: centos7-s2i-web-app:latest
          incremental: true
      output:
        to:
          kind: ImageStreamTag
          name: testing-welcome:latest
      resources:
        {}
      postCommit:
        {}
      nodeSelector: null
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: testing-welcome
      creationTimestamp: null
      labels:
        app: testing
        apptype: welcome
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      strategy:
        resources:
          {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - testing-welcome
            from:
              kind: ImageStreamTag
              name: testing-welcome:latest
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: testing-welcome
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: testing-welcome
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
        spec:
          containers:
            - name: testing-welcome
              image: testing-welcome:latest
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                {}
              env:
                []
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: testing-welcome
      creationTimestamp: null
      labels:
        app: testing
        apptype: welcome
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: testing-welcome
    status:
      loadBalancer:
        {}
  - apiVersion: v1
    kind: Route
    metadata:
      name: testing-welcome-route
      labels:
        app: testing
        apptype: welcome
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: testing-welcome
